# Generated by Django 5.1.5 on 2025-03-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/images/')),
                ('category', models.CharField(choices=[('coffee', 'Coffe-Based Drinks'), ('non_coffee', 'Non-Coffee Drinks'), ('cold', 'Cold & Blended Drinks'), ('food', 'Food & Pastries')], default='coffee', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
