# Generated by Django 5.1.5 on 2025-04-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('coffee', 'Coffee-Based Drinks'), ('non_coffee', 'Non-Coffee Drinks'), ('cold', 'Cold & Blended Drinks'), ('food', 'Food & Pastries')], default='coffee', max_length=20),
        ),
    ]
