# Generated by Django 5.1.5 on 2025-04-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Coffee-Based Drinks', 'Coffee-Based Drinks'), ('Non-Coffee Drinks', 'Non-Coffee Drinks'), ('Cold & Blended Drinks', 'Cold & Blended Drinks'), ('Food & Pastries', 'Food & Pastries')], default='Coffee-Based Drinks', max_length=50),
        ),
    ]
